AWSTemplateFormatVersion: 2010-09-09
Description: >
  MysteryShopper S3 + Lambda Cloudformation example deployment bucket for CF files + Lambda zips

Parameters:
  YourName:
    Type: String
    Description: Enter your name, in format 'first-last', used as the prefix of the S3 bucket name
    Default: Roast-me-DELON16

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${YourName}-raw-deployment-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: Name
          Value: !Sub '${YourName}-raw-deployment-bucket'

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: "AllowSSLRequestsOnly"
            Action: "s3:*"
            Principal: "*"
            Effect: "Deny"
            Resource:
              - !Sub "arn:aws:s3:::${YourName}-raw-deployment-bucket"
              - !Sub "arn:aws:s3:::${YourName}-raw-deployment-bucket/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
